/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mundusprofundis;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Andre Chateaubriand
 */
public class ServerSelectScreen extends javax.swing.JDialog {

    public static String server = "localhost";

    /**
     * Creates new form ServerSelectScreen
     */
    public ServerSelectScreen() {
        initComponents();
        setSize(250, 300);
        panel.setSize(250, 300);
        setLocationRelativeTo(null);
        btOk.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        rdServer = new javax.swing.JRadioButton();
        rdLocalhost = new javax.swing.JRadioButton();
        rdPersonalisado = new javax.swing.JRadioButton();
        tfPersonalisado = new javax.swing.JTextField();
        btOk = new javax.swing.JButton();
        tfTexto = new javax.swing.JTextArea();
        lbTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Servidor");
        getContentPane().setLayout(null);

        panel.setBackground(new java.awt.Color(51, 51, 51));
        panel.setLayout(null);

        rdServer.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rdServer);
        rdServer.setForeground(new java.awt.Color(204, 204, 204));
        rdServer.setSelected(true);
        rdServer.setText("jogo.andrechateau.com");
        rdServer.setBorder(null);
        rdServer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rdServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdServerActionPerformed(evt);
            }
        });
        panel.add(rdServer);
        rdServer.setBounds(10, 100, 210, 20);

        rdLocalhost.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rdLocalhost);
        rdLocalhost.setForeground(new java.awt.Color(204, 204, 204));
        rdLocalhost.setText("localhost");
        rdLocalhost.setBorder(null);
        rdLocalhost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLocalhostActionPerformed(evt);
            }
        });
        panel.add(rdLocalhost);
        rdLocalhost.setBounds(10, 130, 210, 20);

        rdPersonalisado.setBackground(new java.awt.Color(51, 51, 51));
        buttonGroup1.add(rdPersonalisado);
        rdPersonalisado.setForeground(new java.awt.Color(204, 204, 204));
        rdPersonalisado.setText("Outro:");
        rdPersonalisado.setBorder(null);
        panel.add(rdPersonalisado);
        rdPersonalisado.setBounds(10, 160, 59, 20);

        tfPersonalisado.setBackground(new java.awt.Color(102, 102, 102));
        tfPersonalisado.setForeground(new java.awt.Color(51, 51, 51));
        tfPersonalisado.setText("192.168.0.4");
        tfPersonalisado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        panel.add(tfPersonalisado);
        tfPersonalisado.setBounds(80, 160, 130, 22);

        btOk.setBackground(new java.awt.Color(102, 102, 102));
        btOk.setForeground(new java.awt.Color(204, 204, 204));
        btOk.setText("Ok");
        btOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        btOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btOkKeyPressed(evt);
            }
        });
        panel.add(btOk);
        btOk.setBounds(20, 210, 190, 32);

        tfTexto.setEditable(false);
        tfTexto.setBackground(new java.awt.Color(51, 51, 51));
        tfTexto.setColumns(20);
        tfTexto.setForeground(new java.awt.Color(0, 0, 0));
        tfTexto.setRows(5);
        tfTexto.setText("    Arquivo de configuração do servidor\n não encontrado. Porfavor selecione um\nhost desejado para conectar-se.");
        tfTexto.setAutoscrolls(false);
        tfTexto.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        tfTexto.setEnabled(false);
        tfTexto.setFocusable(false);
        panel.add(tfTexto);
        tfTexto.setBounds(10, 40, 220, 50);

        lbTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbTitulo.setText("Seleção de Servidor:");
        panel.add(lbTitulo);
        lbTitulo.setBounds(20, 10, 190, 16);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 240, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdLocalhostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdLocalhostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdLocalhostActionPerformed

    private void rdServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdServerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdServerActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if (rdServer.isSelected()) {
            server = rdServer.getText();
        } else if (rdLocalhost.isSelected()) {
            server = rdLocalhost.getText();
        } else if (rdPersonalisado.isSelected()) {
            server = rdPersonalisado.getText();
        }
        dispose();
    }//GEN-LAST:event_btOkActionPerformed

    private void btOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btOkKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btOkActionPerformed(null);
        }
    }//GEN-LAST:event_btOkKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panel;
    private javax.swing.JRadioButton rdLocalhost;
    private javax.swing.JRadioButton rdPersonalisado;
    private javax.swing.JRadioButton rdServer;
    private javax.swing.JTextField tfPersonalisado;
    private javax.swing.JTextArea tfTexto;
    // End of variables declaration//GEN-END:variables
}
